### ISSUE TITLE
The version on stackblitz is out of sync

### ISSUE THREAD

**Issue by bulldog98** [nilsmehlhorn/ngx-pagination-data-source-example#3]
The [version](https://stackblitz.com/github/nilsmehlhorn/ngx-pagination-data-source-example) is out of sync with this repo.

**Comment by nilsmehlhorn** [comment]
For me that's not the case. There's no version specified for StackBlitz, it just always runs the latest repository version :thinking:

**Comment by bulldog98** [comment]
Now it also works for me, maybe there was still some cache?
